"""Sprint 12 Bit 12.1 — config.py relocation to bot/config.py (2026-05-12).

Moves repo-root `config.py` (157 LOC, Python constants: probability/EGARCH/
position-sizing) → `bot/config.py`. Per L32 Plan-agent verdict, the
master-plan "consolidate config.py + config.json + dist_config.json"
framing is structurally wrong on 2 of 3 files:
  - config.json is auto-generated by scripts/ops/extract_config.py (zero
    bot/ runtime consumers) — KEEP AS-IS.
  - dist_config.json is calibration output written by
    scripts/ops/calibrate_dist.py — KEEP AS-IS.
  - config.py (this Bit) is the only Python source — MOVE.

Per `feedback_modularization_skip_soak.md`: no shim, no soak.
Filename preserved (config.py → bot/config.py).

L32 Plan-agent pre-flight (CRITICAL × 4):
  C1 — bot/runtime_config.py:43 `import config as _cf` is the PEP-562
       dual-probe bridge (Bit 9.3-iii.c). Retarget in same atomic commit
       or dashboard kill-switch contract breaks silently.
  C2 — config.py:38 DIST_CONFIG_PATH = "dist_config.json" is CWD-relative.
       Post-move, mac dry-runs + tests changing CWD silently fall back to
       Student-t(df=4) defaults. Bit 10.4 R1-class lesson; anchor via
       2-level __file__ chain (bot/config.py → bot/ → repo/).
  C3 — scripts/audit/doc_drift_check.py:35 SOURCE_FILES literal "config.py"
       (+ stale "bot/_impl.py" from pre-9.3-iii.c). make doc-drift
       silently drops 9 constants if not retargeted.
  C4 — scripts/ops/extract_config.py:23 BOT_PATH stale + needs CONFIG_PY_PATH
       to read bot/config.py source. Else whitepaper.yml auto-regen
       produces config.json with MAX_RISK_PER_TRADE missing (L82 race).

Fix pattern for C2 (matches bot/engines/weather_engine.py:806-807, the
Bit-3.x precedent for non-leaf bot/ modules anchoring repo-root data):

    _REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

For bot/config.py → bot/ → repo/, the 2-level dirname chain (NOT
3-level; that's for bot/<subpkg>/X.py) anchors back to the repo root.

R5 (.importlinter): helpers-leaf forbidden_modules must add `bot.config`;
no `ignore_imports` carve-out — bot/helpers/*.py has zero references to
config.py (verified pre-flight: today helpers import from bot.constants
exclusively).
"""
from __future__ import annotations

import ast
import configparser
import importlib
import os
import sys
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))


OLD_FILE = REPO_ROOT / "config.py"
NEW_FILE = REPO_ROOT / "bot" / "config.py"


# Names that live in config.py today (verified by reading
# /Users/gabrielkagan/Documents/kalshi-bot/config.py lines 17-157).
EXPECTED_NAMES = (
    # Assets
    "ASSETS",
    # Probability engine
    "VOL_RETURN_INTERVAL",
    "SECONDS_PER_YEAR",
    "DVOL_ANNUALIZED_TO_5S",
    "STUDENT_T_DF",
    "BETA_SLOPE",
    "MAX_EFFECTIVE_PROB",
    "NUMERICAL_SAFETY_CEILING",
    # Distribution
    "DIST_CONFIG_PATH",
    "DIST_CONFIG",
    # EGARCH
    "EGARCH_SHADOW_MODE",
    "EGARCH_STATE_PATH",
    "EGARCH_BUFFER_SAVE_INTERVAL",
    "EGARCH_REFIT_INTERVAL",
    "EGARCH_MIN_RETURNS",
    "EGARCH_RETURN_MAXLEN",
    "EGARCH_MLE_EWL_LAMBDA",
    "EGARCH_WARMUP_RETURNS",
    "EGARCH_E_ABS_Z",
    "EGARCH_LOG_VAR_FLOOR",
    "EGARCH_LOG_VAR_CEILING",
    "EGARCH_MLE_MAXITER",
    "EGARCH_OMEGA_BOUNDS",
    "EGARCH_ALPHA_BOUNDS",
    "EGARCH_GAMMA_BOUNDS",
    "EGARCH_BETA_BOUNDS",
    "EGARCH_DF_BOUNDS",
    "EGARCH_DF_DEFAULT",
    "EGARCH_REFIT_INTERVALS",
    "EGARCH_GAMMA_CONSTRAINTS",
    # EGARCH-RV blend
    "EGARCH_BLEND_SHADOW_MODE",
    "EGARCH_BLEND_STATE_PATH",
    "MZ_WINDOW",
    "MZ_MIN_OBS",
    "MZ_RECOMPUTE_INTERVAL",
    "MZ_EMA_LAMBDA",
    "MZ_EQUAL_WEIGHT_R2_THRESHOLD",
    "MZ_SIGMOID_SHADOW_MODE",
    "MZ_SIGMOID_KAPPA",
    "MZ_SIGMOID_Q_MID",
    "MZ_SIGMOID_W_MAX",
    "EGARCH_WEIGHT_BOUNDS",
    "EGARCH_WEIGHT_DEFAULT",
    "EGARCH_RV_RATIO_CLAMP",
    "EGARCH_BLEND_LOG_INTERVAL",
    # Sizing
    "SIZING_TIERS",
    "DRAWDOWN_HALF_THRESHOLD",
    "DRAWDOWN_QUARTER_THRESHOLD",
    "DRAWDOWN_HALT_THRESHOLD",
    "HWM_LOOKBACK_SECONDS",
    "MAX_RISK_PER_TRADE",
)


# ═════════════════════════════════════════════════════════════════════════════
# Section 1 — Filesystem layout
# ═════════════════════════════════════════════════════════════════════════════


def test_old_repo_root_config_py_is_gone():
    """config.py DELETED from repo root post-move (no shim per skip-soak)."""
    assert not OLD_FILE.exists(), (
        f"{OLD_FILE.relative_to(REPO_ROOT)} still exists. "
        "Bit 12.1 moves config.py → bot/config.py."
    )


def test_new_bot_config_py_exists():
    """bot/config.py EXISTS and is a regular file (not a symlink)."""
    assert NEW_FILE.exists(), f"{NEW_FILE.relative_to(REPO_ROOT)} missing."
    assert NEW_FILE.is_file(), f"{NEW_FILE.relative_to(REPO_ROOT)} is not a regular file."
    assert not NEW_FILE.is_symlink(), (
        f"{NEW_FILE.relative_to(REPO_ROOT)} is a symlink — Bit 12.1 moves "
        "the file, not aliases it (per skip-soak no-shim rule)."
    )


# ═════════════════════════════════════════════════════════════════════════════
# Section 2 — Importability smoke
# ═════════════════════════════════════════════════════════════════════════════


def test_bot_config_imports_clean():
    """`import bot.config` succeeds without ImportError.

    NOTE: we deliberately DO NOT del sys.modules['bot.config'] before the
    re-import. Reloading the module creates fresh float objects (the EGARCH
    bounds, NUMERICAL_SAFETY_CEILING, BETA_SLOPE) — and `bot.engines.*` modules
    captured `from bot.config import ...` references at pytest collection time.
    A reload would break their identity (`is`) checks in
    `test_engines_extraction.py::test_*_config_constants_resolve_from_config`.
    A plain `import bot.config` against the cached module is sufficient for
    the importability assertion.
    """
    import bot.config  # noqa: F401


@pytest.mark.parametrize("name", EXPECTED_NAMES)
def test_bot_config_exports_expected_name(name):
    """Every name from old config.py is reachable from bot.config."""
    import bot.config as cfg
    assert hasattr(cfg, name), (
        f"bot.config is missing {name!r} — Bit 12.1 must preserve every "
        "public binding from the old config.py."
    )


def test_old_config_module_not_importable():
    """`import config` raises ModuleNotFoundError (no compat shim)."""
    for k in list(sys.modules):
        if k == "config" or k.startswith("config."):
            del sys.modules[k]
    with pytest.raises(ModuleNotFoundError):
        importlib.import_module("config")


# ═════════════════════════════════════════════════════════════════════════════
# Section 3 — Stale `from config import` / `import config` AST sweep
# ═════════════════════════════════════════════════════════════════════════════
#
# Walks bot/**/*.py + scripts/**/*.py + tests/**/*.py and asserts ZERO
# executable ImportFrom(module='config') / Import(name='config') nodes.
# Allowed exceptions:
#   - this file (assertion-literal sites are intentional)
#   - tests/contracts/test_bit_9_3_iii_b_proxy_retirement.py (historical
#     proxy-retirement test references)
#   - tests/contracts/test_bit_9_3_iii_c_impl_deletion.py (historical
#     impl-deletion test references)


_AST_SWEEP_DIRS = ("bot", "scripts", "tests")
_AST_SWEEP_DIR_ROOTS = tuple(REPO_ROOT / d for d in _AST_SWEEP_DIRS)
_AST_SWEEP_ALLOWLIST = {
    # This file references "config" in literals for assertion targets.
    "tests/contracts/test_bit_12_1_config_consolidation.py",
}


def _path_in_sweep_scope(path):
    """True if path is under bot/, scripts/, or tests/ and not allowlisted.

    Bit-4.5 (2026-05-17): replaces ``_collect_python_files`` which
    rglob'd the 3 dirs directly. The audit now filters from the
    canonical 4-glob ``repo_ast_cache`` to its narrower scope (3 dirs,
    excludes repo-root *.py).
    """
    if not any(root in path.parents for root in _AST_SWEEP_DIR_ROOTS):
        return False
    rel = path.relative_to(REPO_ROOT).as_posix()
    if rel in _AST_SWEEP_ALLOWLIST:
        return False
    return True


def test_no_stale_from_config_imports_in_executable_code(repo_ast_cache):
    """No file under bot/, scripts/, tests/ has `from config import ...`.

    Bit-4.5 (2026-05-17): consumes session-scoped ``repo_ast_cache``
    filtered to bot/+scripts/+tests/ (subset of 4-glob).
    """
    violations = []
    for path, tree in repo_ast_cache.items():
        if tree is None:
            continue
        if not _path_in_sweep_scope(path):
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom) and node.module == "config":
                violations.append(f"{path.relative_to(REPO_ROOT)}:{node.lineno}")
    assert not violations, (
        f"{len(violations)} stale `from config import ...` sites:\n  "
        + "\n  ".join(violations)
        + "\nBit 12.1: retarget each to `from bot.config import ...`."  # noqa: W605
    )


def test_no_stale_import_config_in_executable_code(repo_ast_cache):
    """No file under bot/, scripts/, tests/ has `import config` (top-level alias).

    Bit-4.5 (2026-05-17): consumes session-scoped ``repo_ast_cache``
    filtered to bot/+scripts/+tests/ (subset of 4-glob).
    """
    violations = []
    for path, tree in repo_ast_cache.items():
        if tree is None:
            continue
        if not _path_in_sweep_scope(path):
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if alias.name == "config":
                        violations.append(
                            f"{path.relative_to(REPO_ROOT)}:{node.lineno}"
                        )
    assert not violations, (
        f"{len(violations)} stale `import config` sites:\n  "
        + "\n  ".join(violations)
        + "\nBit 12.1: retarget each to `import bot.config` "
        "(or `import bot.config as config` if the local alias is load-bearing)."
    )


# ═════════════════════════════════════════════════════════════════════════════
# Section 4 — __file__-derived path resolution pin (C2 fix lock)
# ═════════════════════════════════════════════════════════════════════════════


def test_dist_config_path_anchored_to_ops_runtime():
    """C2 (post Sprint 14-A Bit 3, 2026-05-17, ticket 86b9zfbt8): DIST_CONFIG_PATH
    resolves to <repo>/ops/runtime/dist_config.json, NOT <repo>/dist_config.json
    (pre-Bit-3 location) or <repo>/bot/dist_config.json. Post-move silent-drift
    guard — pins the 3-segment tail so a future renamer cannot silently regress
    to a CWD-relative or wrong-anchor path."""
    import bot.config as cfg
    p = Path(cfg.DIST_CONFIG_PATH)
    assert p.is_absolute(), (
        f"DIST_CONFIG_PATH must be absolute (anchored via __file__); got {p!r}"
    )
    assert p.parts[-3:] == ("ops", "runtime", "dist_config.json"), (
        f"DIST_CONFIG_PATH must resolve to <repo>/ops/runtime/dist_config.json "
        f"post Sprint 14-A Bit 3 root-cleanup move; got {p!r}"
    )
    assert p.parent.parent.parent == REPO_ROOT, (
        f"DIST_CONFIG_PATH must be anchored to repo root via __file__; "
        f"got grandparent.parent={p.parent.parent.parent!r}, REPO_ROOT={REPO_ROOT!r}"
    )


def test_egarch_state_path_anchored_to_repo_root():
    """N3: EGARCH_STATE_PATH same __file__-anchor concern as DIST_CONFIG_PATH."""
    import bot.config as cfg
    p = Path(cfg.EGARCH_STATE_PATH)
    assert p.is_absolute(), f"EGARCH_STATE_PATH must be absolute; got {p!r}"
    assert p.parent == REPO_ROOT
    assert p.name == "egarch_state.json"


def test_egarch_blend_state_path_anchored_to_repo_root():
    """N3: EGARCH_BLEND_STATE_PATH same __file__-anchor concern."""
    import bot.config as cfg
    p = Path(cfg.EGARCH_BLEND_STATE_PATH)
    assert p.is_absolute(), f"EGARCH_BLEND_STATE_PATH must be absolute; got {p!r}"
    assert p.parent == REPO_ROOT
    assert p.name == "egarch_blend_state.json"


# ═════════════════════════════════════════════════════════════════════════════
# Section 5 — Naive `os.path.dirname(__file__)` ban
# ═════════════════════════════════════════════════════════════════════════════


def test_bot_config_no_naive_dirname_pattern():
    """bot/config.py source must not contain the 1-level naive pattern.
    Same Bit-10.4 R1-fix-class anti-regression."""
    src = NEW_FILE.read_text()
    # Allow the 2-level chain (`os.path.dirname(os.path.dirname(...))`) but
    # ban the bare 1-level pattern.
    naive_pattern = "os.path.dirname(__file__)"
    # The 2-level chain begins `os.path.dirname(os.path.dirname(`; the bare
    # naive pattern appears as `os.path.dirname(__file__)` directly.
    assert naive_pattern not in src or "os.path.dirname(os.path.dirname" in src, (
        "bot/config.py uses naive os.path.dirname(__file__) — must use "
        "2-level dirname chain `os.path.dirname(os.path.dirname(os.path.abspath(__file__)))`."
    )


# ═════════════════════════════════════════════════════════════════════════════
# Section 6 — .importlinter helpers-leaf coverage
# ═════════════════════════════════════════════════════════════════════════════


def test_importlinter_helpers_leaf_forbids_bot_config():
    """`.importlinter` [helpers-leaf] forbidden_modules must include `bot.config`.

    bot.config is a constants leaf module (mirrors bot.constants role); helpers
    must not back-edge into it. The peer test in test_import_linter_contracts.py
    walks bot/ at test time and asserts every new top-level module is listed —
    this test additionally locks the literal so the wiring is direct."""
    cfg = configparser.ConfigParser()
    cfg.read(REPO_ROOT / ".importlinter")
    section = "importlinter:contract:helpers-leaf"
    assert cfg.has_section(section)
    forbidden = cfg.get(section, "forbidden_modules")
    forbidden_set = {line.strip() for line in forbidden.splitlines() if line.strip()}
    assert "bot.config" in forbidden_set, (
        f"`.importlinter` [{section}] forbidden_modules is missing `bot.config`. "
        f"Current entries: {sorted(forbidden_set)}"
    )


# ═════════════════════════════════════════════════════════════════════════════
# Section 7 — bot/runtime_config.py retarget pin (C1)
# ═════════════════════════════════════════════════════════════════════════════


def test_runtime_config_imports_bot_config_not_config():
    """C1: bot/runtime_config.py PEP-562 dual-probe must target bot.config,
    not the now-deleted top-level `config` module. Same atomic commit."""
    src = (REPO_ROOT / "bot" / "runtime_config.py").read_text()
    tree = ast.parse(src)
    found_target = False
    forbidden_targets = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name == "bot.config":
                    found_target = True
                if alias.name == "config":
                    forbidden_targets.append(f"line {node.lineno}: import config")
        elif isinstance(node, ast.ImportFrom):
            if node.module == "config":
                forbidden_targets.append(
                    f"line {node.lineno}: from config import {[a.name for a in node.names]}"
                )
    assert found_target, (
        "bot/runtime_config.py must `import bot.config` (post-Bit-12.1)."
    )
    assert not forbidden_targets, (
        "bot/runtime_config.py has stale config imports:\n  "
        + "\n  ".join(forbidden_targets)
    )


# ═════════════════════════════════════════════════════════════════════════════
# Section 8 — PEP-562 mutation-freshness smoke (Bit-9.3-iii.c contract)
# ═════════════════════════════════════════════════════════════════════════════


def test_runtime_config_dual_probe_reaches_bot_config_constants():
    """The PEP-562 dual-probe must continue to surface bot.config constants
    on each access — locks the Bit-9.3-iii.c kill-switch contract against
    Bit-12.1 regression."""
    import bot.config as cfg
    import bot.runtime_config as rc

    # Pick a name that lives in config.py (NOT bot.constants), so the
    # dual-probe must reach the second leg.
    sentinel = "__bit_12_1_sentinel__"
    original = getattr(cfg, "EGARCH_BLEND_SHADOW_MODE", None)
    try:
        cfg.EGARCH_BLEND_SHADOW_MODE = sentinel
        # Re-read through runtime_config — PEP-562 __getattr__ must dual-probe
        # bot.constants → bot.config and find the sentinel on the second probe.
        assert rc.EGARCH_BLEND_SHADOW_MODE == sentinel, (
            "bot.runtime_config dual-probe failed to surface mutated "
            "bot.config attribute — Bit-9.3-iii.c kill-switch contract broken."
        )
    finally:
        if original is None:
            try:
                del cfg.EGARCH_BLEND_SHADOW_MODE
            except AttributeError:
                pass
        else:
            cfg.EGARCH_BLEND_SHADOW_MODE = original


# ═════════════════════════════════════════════════════════════════════════════
# Section 9 — scripts/audit/doc_drift_check.py SOURCE_FILES retarget (C3)
# ═════════════════════════════════════════════════════════════════════════════


def test_doc_drift_check_source_files_retargeted():
    """C3: scripts/audit/doc_drift_check.py SOURCE_FILES must list `bot/config.py`
    (post-move) and must NOT list bare `config.py`. The stale `bot/_impl.py`
    entry from pre-9.3-iii.c is bundled-fixed in the same Bit (cleanup)."""
    src = (REPO_ROOT / "scripts" / "audit" / "doc_drift_check.py").read_text()
    tree = ast.parse(src)
    # Find SOURCE_FILES assignment.
    source_files_node = None
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id == "SOURCE_FILES":
                    source_files_node = node.value
                    break
    assert source_files_node is not None, (
        "scripts/audit/doc_drift_check.py SOURCE_FILES symbol not found."
    )
    # Extract string literals from the list/tuple.
    paths = []
    if isinstance(source_files_node, (ast.List, ast.Tuple)):
        for elt in source_files_node.elts:
            if isinstance(elt, ast.Constant) and isinstance(elt.value, str):
                paths.append(elt.value)
    assert "bot/config.py" in paths, (
        f"SOURCE_FILES must include `bot/config.py`; current: {paths}"
    )
    assert "config.py" not in paths, (
        f"SOURCE_FILES still has stale bare `config.py`; current: {paths}"
    )


# ═════════════════════════════════════════════════════════════════════════════
# Section 10 — scripts/ops/extract_config.py extends to bot/config.py (C4)
# ═════════════════════════════════════════════════════════════════════════════


def test_extract_config_reads_bot_config_py():
    """C4: scripts/ops/extract_config.py must read bot/config.py source so
    config.json auto-regen includes MAX_RISK_PER_TRADE / DRAWDOWN_* /
    HWM_LOOKBACK_SECONDS / EGARCH_* etc. after Bit 12.1."""
    src = (REPO_ROOT / "scripts" / "ops" / "extract_config.py").read_text()
    # The script names path constants for each source file; assert the
    # bot/config.py source path is referenced.
    assert "bot/config.py" in src, (
        "scripts/ops/extract_config.py does not reference `bot/config.py` — "
        "Bit 12.1 must extend the source set so config.json auto-regen "
        "captures the relocated constants."
    )


def test_extract_config_no_stale_bare_config_py_reference():
    """C4 cleanup: the script must not still treat bare `config.py` as a
    source — that path no longer exists post-move."""
    src = (REPO_ROOT / "scripts" / "ops" / "extract_config.py").read_text()
    # We can't ban the bare substring "config.py" entirely (it's a suffix of
    # "bot/config.py"). Instead AST-walk for ast.Constant string literals.
    tree = ast.parse(src)
    bare_refs = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            # Exact match `config.py` only.
            if node.value == "config.py":
                bare_refs.append(f"line {node.lineno}: {node.value!r}")
    assert not bare_refs, (
        "scripts/ops/extract_config.py still has bare `config.py` string "
        "literals (the file moved to bot/config.py):\n  " + "\n  ".join(bare_refs)
    )
