#!/usr/bin/env python3
"""Phase G-6: one-time stamp `data_provenance` on existing rows.

Decision rule (conservative — see
kb/decisions/v2-train-must-account-for-backfill-skew-may02.md):

  Phase F-3 deploy: 2026-05-02T19:53:19Z (commit 4897846). After this
  timestamp, btc/eth/sol/xrp_spot_at_decision, time_above/below_strike,
  maker counterfactual, and knockout_time_relative were ALL captured
  live (sub-second precision). Before this timestamp at least one of
  these column-groups was either NULL or backfilled from 1-min Coinbase
  candles by Phase G-2/G-4.

  We use the LATEST Phase F sub-deploy (F-3, 19:53:19Z) — not the
  earliest (F, 19:07:45Z) — so 'live_ws' is a strict subset where every
  Phase F column is live. This conservatively excludes ~46 minutes of
  rows captured between F and F-3 from the held-out validation set;
  acceptable trade-off for v2 (per adversarial review round 1 #5).

Vocabulary (matches v2-train doc spec lines 78-83):
  - 'live_ws'             — fully live capture, all Phase F columns present
  - 'backfill_60s_inputs' — at least one Phase F column came from G-2/G-4
                            (1-min Coinbase candles → 60-second precision)
  - 'backfill_sql_only'   — G-1/G-5 only (no G-2/G-4 60s skew). Spec
                            (v2-train doc lines 82-83) defines this as
                            "G-1/G-5 only; G-2/G-4 cols populated LIVE
                            or N/A". Under CURRENT data the value is
                            UNREACHABLE: G-2 backfilled
                            btc_spot_at_decision on 100% of pre-cutoff
                            rows, so every pre-cutoff row falls into
                            'backfill_60s_inputs' instead.
                            TODO: this branch is intentionally NOT
                            generated by this script. If a future use
                            case ever needs it, the predicate must
                            distinguish "G-2/G-4 cols are LIVE" (which
                            requires per-row provenance metadata we
                            don't currently capture) from "G-2/G-4 cols
                            are N/A". Today we have neither, so the
                            value is undefined. Reconcile with spec
                            wording before activating.
  - NULL                  — pre-Phase-F row with NO inputs anywhere
                            (useless for v2 training, left NULL)

Stamping logic:
  - product_type='15m' AND evaluation_time < '2026-05-02T19:53:19.000000Z'
    AND (btc_spot_at_decision IS NOT NULL OR
         time_above_strike_seconds IS NOT NULL)
    → 'backfill_60s_inputs'
  - product_type='15m' AND evaluation_time >= '2026-05-02T19:53:19.000000Z'
    → 'live_ws'
  - product_type='15m' AND evaluation_time < cutoff AND no inputs → leave NULL
  - Non-15m rows → leave NULL (cal_mlp pipeline scopes to 15m only).

  Cutoff string carries microseconds because bot.py timestamps use
  '%Y-%m-%dT%H:%M:%S.%fZ'. A naive 'YYYY-MM-DDTHH:MM:SSZ' cutoff lexically
  sorts AFTER all microsecond-bearing strings of the same second
  (because '.' < 'Z' in ASCII), which would misclassify rows in the cutoff
  second as pre-cutoff (round-1 adversarial review #4).

Interaction with H-4 backfills (gdelt/glassnode/cryptocompare):
  Those scripts use UPDATE ... SET data_provenance = COALESCE(
  data_provenance, '<source>'). After this stamp script runs, every 15m
  row has a non-NULL value, so H-4 source markers ('backfill_glassnode_*'
  etc.) NEVER overwrite. This is acceptable for v2 (v2 filters on
  'live_ws' for held-out only, 'backfill_60s_inputs' for train-only).
  If finer-grained source-attribution is needed later, introduce a
  separate column rather than overloading this one.

Idempotent: re-runs no-op via `WHERE data_provenance IS NULL` filter.
Safe under live bot writes — the live bot always writes 'live_ws' on
insert (per Phase G-6 bot.py edit), so any new rows already have a value.

Usage:
  python3 scripts/backfill/stamp_data_provenance.py --db state.db
  python3 scripts/backfill/stamp_data_provenance.py --db state.db --dry-run
"""

from __future__ import annotations

import argparse
import logging
import sqlite3
import sys
import time as _time

logger = logging.getLogger(__name__)

# Phase F-3 deploy time (commit 4897846, 2026-05-02T15:53:19-04:00 →
# 19:53:19Z). Microseconds in the literal so lexical comparison with
# bot.py's `%Y-%m-%dT%H:%M:%S.%fZ` timestamps is correct (round 1 #4).
PHASE_F3_DEPLOY_ISO = "2026-05-02T19:53:19.000000Z"


def stamp(
    conn: sqlite3.Connection,
    batch_size: int = 50,
    sleep_ms: int = 50,
    dry_run: bool = False,
) -> dict:
    """Stamp data_provenance on all 15M rows where it's still NULL.

    Batched UPDATE pattern enforces CLAUDE.md "DB write batches: ≤50 rows
    per commit" — larger commits hold the SQLite write lock long enough
    to deadlock concurrent bot inserts under busy_timeout=10000ms. Since
    this script runs against a live bot DB, the default is 50.
    Operators running offline (bot stopped) can pass `--batch-size 5000`
    for ~50× speedup on the 80K-row stamp.

    Returns metrics dict with keys: 'backfill_60s_inputs', 'live_ws',
    'examined', 'leave_null_pre_phase_f' (consistent shape across
    dry-run and actual modes per round-2 #12 / round-1 #17).
    """
    metrics = {
        "backfill_60s_inputs": 0,
        "live_ws": 0,
        "examined": 0,
        "leave_null_pre_phase_f": 0,
    }

    if dry_run:
        n_bf = conn.execute(
            """SELECT COUNT(*) FROM evaluated_opportunities
               WHERE product_type='15m'
                 AND data_provenance IS NULL
                 AND evaluation_time < ?
                 AND (btc_spot_at_decision IS NOT NULL
                      OR time_above_strike_seconds IS NOT NULL)""",
            (PHASE_F3_DEPLOY_ISO,),
        ).fetchone()[0]
        n_lw = conn.execute(
            """SELECT COUNT(*) FROM evaluated_opportunities
               WHERE product_type='15m'
                 AND data_provenance IS NULL
                 AND evaluation_time >= ?""",
            (PHASE_F3_DEPLOY_ISO,),
        ).fetchone()[0]
        n_skipped = conn.execute(
            """SELECT COUNT(*) FROM evaluated_opportunities
               WHERE product_type='15m'
                 AND data_provenance IS NULL
                 AND evaluation_time < ?
                 AND btc_spot_at_decision IS NULL
                 AND time_above_strike_seconds IS NULL""",
            (PHASE_F3_DEPLOY_ISO,),
        ).fetchone()[0]
        metrics["backfill_60s_inputs"] = n_bf
        metrics["live_ws"] = n_lw
        metrics["examined"] = n_bf + n_lw
        metrics["leave_null_pre_phase_f"] = n_skipped
        logger.info("[DRY RUN] would stamp: %s", metrics)
        return metrics

    # Pre-actual-run snapshot of leave-null rows for parity with dry-run.
    # Captured BEFORE the UPDATEs so it reflects what the script left alone.
    pre_skipped = conn.execute(
        """SELECT COUNT(*) FROM evaluated_opportunities
           WHERE product_type='15m'
             AND data_provenance IS NULL
             AND evaluation_time < ?
             AND btc_spot_at_decision IS NULL
             AND time_above_strike_seconds IS NULL""",
        (PHASE_F3_DEPLOY_ISO,),
    ).fetchone()[0]
    metrics["leave_null_pre_phase_f"] = pre_skipped

    # Batched UPDATE for 'backfill_60s_inputs'. Use rowid-windowed loop
    # so each commit holds the write lock for a bounded number of rows.
    while True:
        cur = conn.execute(
            """UPDATE evaluated_opportunities
               SET data_provenance = 'backfill_60s_inputs'
               WHERE rowid IN (
                   SELECT rowid FROM evaluated_opportunities
                   WHERE product_type='15m'
                     AND data_provenance IS NULL
                     AND evaluation_time < ?
                     AND (btc_spot_at_decision IS NOT NULL
                          OR time_above_strike_seconds IS NOT NULL)
                   LIMIT ?
               )""",
            (PHASE_F3_DEPLOY_ISO, batch_size),
        )
        n = cur.rowcount
        conn.commit()
        metrics["backfill_60s_inputs"] += n
        if n < batch_size:
            break
        if sleep_ms > 0:
            _time.sleep(sleep_ms / 1000.0)

    # Batched UPDATE for 'live_ws'.
    while True:
        cur = conn.execute(
            """UPDATE evaluated_opportunities
               SET data_provenance = 'live_ws'
               WHERE rowid IN (
                   SELECT rowid FROM evaluated_opportunities
                   WHERE product_type='15m'
                     AND data_provenance IS NULL
                     AND evaluation_time >= ?
                   LIMIT ?
               )""",
            (PHASE_F3_DEPLOY_ISO, batch_size),
        )
        n = cur.rowcount
        conn.commit()
        metrics["live_ws"] += n
        if n < batch_size:
            break
        if sleep_ms > 0:
            _time.sleep(sleep_ms / 1000.0)

    metrics["examined"] = metrics["backfill_60s_inputs"] + metrics["live_ws"]
    logger.info("stamped: %s", metrics)
    return metrics


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="One-time stamp data_provenance on existing 15M rows",
    )
    parser.add_argument("--db", required=True)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--sleep-ms", type=int, default=50)
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
    )

    conn = sqlite3.connect(args.db, timeout=30.0)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA busy_timeout=10000")

    # Verify column exists before attempting to stamp.
    cols = [r[1] for r in conn.execute(
        "PRAGMA table_info(evaluated_opportunities)"
    ).fetchall()]
    if "data_provenance" not in cols:
        logger.error(
            "data_provenance column not found — start the bot once to "
            "trigger ALTER TABLE migration, OR run: ALTER TABLE "
            "evaluated_opportunities ADD COLUMN data_provenance TEXT"
        )
        return 2

    metrics = stamp(conn, sleep_ms=args.sleep_ms, dry_run=args.dry_run)
    conn.close()

    logger.info("done: %s", metrics)
    return 0


if __name__ == "__main__":
    sys.exit(main())
